### PR TITLE
Update version to 2.3.9-SNAPSHOT

### PR DESCRIPTION
**Pull request by vtintillier**
Since 2.3.8 was released with commit
5296d48dc5fd31de55373ed88cf691c9d1863f8f

### CODE REVIEW

**Comment by vtintillier** [comment]
Hello @omalley

can you merge this and release 2.3.9 ?

Thanks
Vivien

**Comment by rharder** [comment]
@vtintillier @omalley I made the merge and release: https://github.com/omalley/base64/releases/tag/release-2.3.9  I'm also updating the sourceforge copy, which has always been the master.  Thanks!

**Comment by omalley** [comment]
Thanks.

**Comment by vtintillier** [comment]
Thank you.
Will you then release to Maven Central as well? I cannot see it yet at [1]

[1] http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22net.iharder%22%20AND%20a%3A%22base64%22

**Comment by omalley** [comment]
Ok, I just pushed the 2.3.9 release to sonatype and so it should show up in Maven Central in a day or so. Since I had to rediscover the process for doing the release, I added them to the README file.

**Comment by vtintillier** [comment]
I can see it now. Thank you Owen and Robert!

**Pull request merged**
